//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 BundleTools 自动生成，请勿手动修改。
//     生成时间：2025/11/07 22:11:45
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjtFramework.AssetFramework
{
    public enum BundleModule
    {
        module1,
    }
}
