using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using tjtFramework.AssetFramework;
using tjtFramework.Utiliy;
using UnityEditor;
using UnityEngine;

public class BundleTools
{
    private static string bundleModuleFilePath = Application.dataPath + 
        "/Scripts/tjtFramework/AssetFramework/Data/BundleModuleEnum.cs";

    [MenuItem("AssetFramework/GenerateBundleModuleEnum")]
    public static void GenerateBundleModuleEnum()
    {
        List<BuildModuleData> moduleList = BuildBundleConfig.Instance.AssetBundleConfig;

        if(moduleList.IsNullOrEmpty())
        {
            Debug.LogError("未在BuildBundleConfig中找到构建包模块数据，生成枚举失败");
            return;
        }

        // 确保目录存在
        string dir = Path.GetDirectoryName(bundleModuleFilePath);
        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        // 构建代码内容
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     此文件由 BundleTools 自动生成，请勿手动修改。");
        sb.AppendLine("//     生成时间：" + System.DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"));
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("namespace tjtFramework.AssetFramework");
        sb.AppendLine("{");
        sb.AppendLine("    public enum BundleModule");
        sb.AppendLine("    {");

        foreach (var module in moduleList)
        {
            if (string.IsNullOrEmpty(module.moduleName))
                continue;

            // 处理非法字符（确保是合法的 C# 标识符）
            string safeName = MakeSafeEnumName(module.moduleName);

            sb.AppendLine($"        {safeName},");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // 删除旧文件（防止残留旧 BOM 或换行符）
        if (File.Exists(bundleModuleFilePath))
        {
            File.Delete(bundleModuleFilePath);
        }
        // 写入文件
        File.WriteAllText(bundleModuleFilePath, sb.ToString(), Encoding.UTF8);

        AssetDatabase.Refresh();

        Debug.Log($"枚举文件生成成功：{bundleModuleFilePath}");
    }

    /// <summary>
    /// 转换模块名为合法的 C# 枚举名
    /// </summary>
    private static string MakeSafeEnumName(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "None";

        // 移除空格和非法字符
        var builder = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                builder.Append(c);
        }

        string result = builder.ToString();

        // 不能以数字开头
        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
